// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TemplateAssignmentBos.Models;

namespace TemplateAssignmentBos.Migrations
{
    [DbContext(typeof(StudentContext))]
    partial class StudentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("TemplateAssignmentBos.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            FirstName = "Mike",
                            Grade = 49,
                            LastName = "Derry"
                        },
                        new
                        {
                            StudentId = 2,
                            FirstName = "Sharon",
                            Grade = 59,
                            LastName = "Stone"
                        },
                        new
                        {
                            StudentId = 3,
                            FirstName = "Sturm",
                            Grade = 69,
                            LastName = "Thurman"
                        },
                        new
                        {
                            StudentId = 4,
                            FirstName = "Bronze",
                            Grade = 79,
                            LastName = "Erat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
